# This GitHub Actions workflow runs on manual trigger on a branch of a
# repository, and configures the React app in the AWS Amplify Console.
#
# First, the GitHub Action deploys the 'stack.yaml' AWS CloudFormation stack
# to your AWS Account. This stack configures the React app in the AWS Amplify Console.
#
# Then, you need to trigger a first build in the AWS Amplify Console to
# fully configure it.

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'

name: Deploy
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
        
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
            name: stack2
            template: stack2.yaml
            #parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"
        
      #- name: deploy
     # uses: appleboy/lambda-action@master
      #  with:
       #   aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         # aws_region: ${{ secrets.AWS_REGION }}
          #function_name: lambda-cd
          #deployment_package: deploy.zip
          #zip_file: deploy.zip
          #source: deploy.zip
